platform = "ollama"
model = "gpt-oss:20b"
api_key = "your api key"

# ollama 参考:
# platform = "ollama"
# model = "deepseek-r1:8b"
# api_key = "your api key"

# siliconflow 参考：
# platform = "siliconflow"
# model = "deepseek-ai/DeepSeek-R1-0528-Qwen3-8B"
# api_key = "your api key"

